# Generated by Django 3.1.3 on 2021-06-11 14:11

import direct.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(max_length=100)),
                ('priority', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=150, validators=[direct.models.val_subject])),
                ('first_message', models.CharField(max_length=250, validators=[direct.models.val_message])),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_text', models.CharField(max_length=250, validators=[direct.models.val_message])),
                ('is_staff', models.BooleanField(default=False)),
                ('message_time', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='direct.chatmodel')),
            ],
            options={
                'ordering': ['message_time'],
            },
        ),
    ]
