# Generated by Django 3.1.3 on 2021-06-11 14:11

import comment.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=200, validators=[comment.models.comment_validator])),
                ('rate', models.IntegerField(validators=[comment.models.rate_validator])),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-create_at'],
            },
        ),
    ]
