# Generated by Django 3.1.3 on 2021-06-14 19:22

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='author',
            field=models.CharField(default='ali', max_length=100, validators=[products.models.product_name_validator]),
        ),
    ]
