# Generated by Django 3.1.3 on 2021-06-22 14:53

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='author',
            field=models.CharField(max_length=100, validators=[products.models.product_name_validator]),
        ),
    ]
